version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: server
    restart: always
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
        consistency: consistent